### ISSUE TITLE
Building PluginPile.RaidImporter doesn't use the translations

### ISSUE THREAD

**Issue by StevensND** [foohyfooh/PKHeXPluginPile#26]
I built PluginPile.RaidImporter using build.ps1.

However is [not using the translations](https://i.imgur.com/hZ4mdAU.png).

![Sin título](https://github.com/foohyfooh/PKHeXPluginPile/assets/45856578/c053bd66-1c18-4fce-843c-ade87f993983)

**Comment by foohyfooh** [comment]
Is it that you started PKHeX with a different language before changing to Spanish or is it that you started PKHeX up on Spanish?
If it is that you changed languages during the running of the program then you would need to restart PKHeX since plugins don't get notified of language change. But if it is that you started PKHeX on Spanish then I will have to look into why it is not using the correct language text.

**Comment by StevensND** [comment]
> Is it that you started PKHeX with a different language before changing to Spanish or is it that you started PKHeX up on Spanish? If it is that you changed languages during the running of the program then you would need to restart PKHeX since plugins don't get notified of language change. But if it is that you started PKHeX on Spanish then I will have to look into why it is not using the correct language text.

I started using English and then switched to Spanish. It wasn't changing so I decided to restart PkHex and it was still not working so I made the post.

However I restart my PC and it's working now. For some reason before it didn't work even if I restarted PKHex.
